src/main/java/org/apache/maven/plugins/dependency/PurgeLocalRepositoryMojo.java

Some minor updates after reviewing it again.
- [ X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

[MDEP-653] - Remove newline and trailing space from log line.

---

src/test/java/org/apache/maven/plugins/dependency/TestGetMojo.java

If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure please ask on the developers list.
To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) you have to acknowledge this by using the following check-box.

[MDEP-664] Restore disabled unit tests for Get goal

---

pom.xml
src/it/projects/mdep-663_analyze_unsupported_version/invoker.properties
src/it/projects/mdep-663_analyze_unsupported_version/pom.xml
src/it/projects/mdep-663_analyze_unsupported_version/src/main/java/Main.java

you have to acknowledge this by using the following check-box.

[MDEP-663] - Update ASM so it works with Java 13

---

src/main/java/org/apache/maven/plugins/dependency/PurgeLocalRepositoryMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/CopyDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/UnpackDependenciesMojo.java

fix JavaDoc errors

---

src/main/java/org/apache/maven/plugins/dependency/PurgeLocalRepositoryMojo.java

remove unused code

---

src/test/java/org/apache/maven/plugins/dependency/utils/TestDependencyUtil.java

remove unthrown exceptions

---

src/site/apt/index.apt.vm

docs: fix typo

---

src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo2.java

cure a deprecation warning

---

src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestUnpackMojo.java

remove debugging code

---

pom.xml
src/main/java/org/apache/maven/plugins/dependency/analyze/AnalyzeDuplicateMojo.java

@michael-o 4.2 is last version that supports Java 7

update to collections4

---

pom.xml

@hboutemy Think I have the integration tests passing now

[MDEP-676] update doxia site tools

---

src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/resolvers/ExcludeReactorProjectsDependencyFilterTest.java
src/test/java/org/apache/maven/plugins/dependency/utils/translators/TestClassifierTypeTranslator.java

Replace more deprecated and unused code

---

.gitignore

add versions backup files to .gitignore

---

pom.xml

[MDEP-702] update commons-lang

---

src/main/java/org/apache/maven/plugins/dependency/analyze/AnalyzeDuplicateMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/BuildClasspathMojo.java
src/main/java/org/apache/maven/plugins/dependency/utils/DependencyUtil.java

use try with resources

---

src/test/java/org/apache/maven/plugins/dependency/testUtils/stubs/DuplicateDependencies2ProjectStub.java
src/test/java/org/apache/maven/plugins/dependency/testUtils/stubs/DuplicateDependenciesProjectStub.java

properly handle encoding and close streams

---

src/main/java/org/apache/maven/plugins/dependency/ListClassesMojo.java
src/test/java/org/apache/maven/plugins/dependency/TestListClassesMojo.java

fix up test names

---

src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java

exceptions fail tests

---

pom.xml

Update maven-dependency-analyzer to 1.11.2

---

src/main/java/org/apache/maven/plugins/dependency/ListClassesMojo.java

@ian-lavallee This class from Jonathan's work hasn't been released yet so there's no API incompatibility

privatize method

---

src/site/apt/index.apt.vm

[MDEP-645] update docs to reflect new target

---

pom.xml

[MDEP-720] update snapshot dependency to non-snapshot

---

src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestIncludeExcludeUnpackDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo2.java
src/test/java/org/apache/maven/plugins/dependency/resolvers/TestResolveMojo.java
src/test/java/org/apache/maven/plugins/dependency/tree/TestTreeMojo_ContainsVersion.java

unused imports and other minor warnings

---

src/main/java/org/apache/maven/plugins/dependency/tree/VerboseDependencyGraphBuilder.java

one dereference per statement to narrow down an NPE

---

src/main/java/org/apache/maven/plugins/dependency/resolvers/AbstractResolveMojo.java

remove Javadoc that has no method

---

src/main/java/org/apache/maven/plugins/dependency/tree/VerboseDependencyGraphBuilder.java

[MDEP-729] fix NullPointerException

---

src/site/apt/examples/copying-project-dependencies.apt.vm
src/site/apt/index.apt.vm
src/site/site.xml

The relative link starting with / is being ignored and the browser tries to open the fowlling link that does not exist:
https://maven.apache.org/plugins/maven-dependency-plugin/guides/introduction/introduction-to-dependency-mechanism.html
Also update http links to https in other pages.
be performed on your pull request …

Use absolute URL for Dependency Mechanism link

---

src/main/java/org/apache/maven/plugins/dependency/filters/AbstractDependencyFilter.java
src/main/java/org/apache/maven/plugins/dependency/filters/ArtifactIdFilter.java
src/main/java/org/apache/maven/plugins/dependency/filters/ClassifierFilter.java
src/main/java/org/apache/maven/plugins/dependency/filters/GroupIdFilter.java
src/main/java/org/apache/maven/plugins/dependency/filters/ScopeFilter.java
src/main/java/org/apache/maven/plugins/dependency/filters/TypeFilter.java

This PR only some methods from child classes to its parent.
To make …

[MDEP-568] Moves similar methods to parent class

---

pom.xml
src/test/java/org/apache/maven/plugins/dependency/TestGetMojo.java

Fix Ci issue

---

pom.xml
src/main/java/org/apache/maven/plugins/dependency/ListClassesMojo.java
src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java
src/main/java/org/apache/maven/plugins/dependency/analyze/AnalyzeDepMgt.java
src/main/java/org/apache/maven/plugins/dependency/analyze/AnalyzeDuplicateMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/AbstractFromConfigurationMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/BuildClasspathMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/CopyDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/ExcludeReactorProjectsDependencyFilter.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/GoOfflineMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/ResolveDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/tree/AbstractVerboseGraphSerializer.java
src/main/java/org/apache/maven/plugins/dependency/tree/ArtifactKey.java
src/main/java/org/apache/maven/plugins/dependency/tree/TreeMojo.java
src/main/java/org/apache/maven/plugins/dependency/tree/VerboseDependencyGraphBuilder.java
src/main/java/org/apache/maven/plugins/dependency/utils/DependencyUtil.java
src/main/java/org/apache/maven/plugins/dependency/utils/filters/MarkerFileFilter.java

Signed-off-by: Olivier Lamy <olamy@apache.org>
To make clear that you …

[MDEP-760] Java 1.8 as minimum

---

src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestUnpackMojo.java

Try to improve test stability on macOS

---

pom.xml

use streamLogsOnFailures to help to investigate failed test on CI
To …

[MDEP-766] Upgrade maven-invoker-plugin to version 3.2.2

---

pom.xml
src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java

[MDEP-784] Upgrade maven-dependency-analyzer to 1.12.0

---

pom.xml

Latest version from 9.4.x without CVE issues
---
To make clear that you …

Update jetty to 9.4.44.v20210927

---

pom.xml

Update mavenPluginTools to 3.6.4

---

src/it/projects/analyze-ignore-dependency/src/test/java/MainTest.java
src/it/projects/analyze-ignore-non-test-scope-dependency/invoker.properties
src/it/projects/analyze-ignore-non-test-scope-dependency/pom.xml
src/it/projects/analyze-ignore-non-test-scope-dependency/src/test/java/MainTest.java
src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java

[MDEP-787] allow ignoring non-test-scoped dependencies

---

src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java
src/site/apt/examples/exclude-dependencies-from-dependency-analysis.apt.vm

[MDEP-789] Improve documentation of analyze - Non-test scoped

---

README.md

(doc) Update link to Github PR docs

---

pom.xml
src/it/projects/analyze-report/invoker.properties
src/it/projects/analyze-report/pom.xml
src/it/projects/analyze-report/verify.bsh

- use maven-site-plugin in IT test
- remove dependency to doxia, it is transitive from maven-reporting-impl
---
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are …

[MDEP-788] Upgrade maven-reporting-impl to version 3.1.0

---

.github/dependabot.yml
pom.xml

Update Jetty to 9.4.45.v20220203 and also ignore in `dependabot.yml` the versions >= 10 of Jetty as are Java 11+ only (dependabot should open PRs only for versions 9.x that are compatible with Java 8) …

[MDEP-795] - Update Jetty to 9.4.45.v20220203

---

pom.xml

[MDEP-796] Upgrade Maven Parent to 35

---

pom.xml

[MDEP-813] Require Maven 3.2.5

---

pom.xml

cleanup override configuration
To make clear that you license your …

[MDEP-815] Upgrade Parent to 37

---

src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java

The parameter `ignoreUnusedRuntime` introduced by #123 was missing a `@since` tag. It appears in that case maven-plugin-tools inherits the `@since` from the Mojo, which is quite confusing:
(Have created [MPLUGIN-420](https://issues.apache.org/jira/browse/MPLUGIN-420) for maven-plugin-tools-generators, questioning whether that behavior is really a good idea.)
is to use the JIRA issue title in the pull request title and in the first …

[MDEP-714] Add missing 'since' to ignoreUnusedRuntime parameter

---

src/main/java/org/apache/maven/plugins/dependency/fromDependencies/AbstractFromDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/CopyDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/UnpackDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/utils/DependencyUtil.java
src/main/java/org/apache/maven/plugins/dependency/utils/filters/DestFileFilter.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo2.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo2.java
src/test/java/org/apache/maven/plugins/dependency/utils/TestDependencyUtil.java
src/test/java/org/apache/maven/plugins/dependency/utils/filters/TestDestFileFilter.java

[MDEP-782] - Add ability to strip type

---

src/main/java/org/apache/maven/plugins/dependency/GetMojo.java

Remove unused fields

---

src/main/java/org/apache/maven/plugins/dependency/ListClassesMojo.java

[MDEP-842] Use skip field in :list-classes

---

src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java

https://issues.apache.org/jira/browse/MNG-6825
To make clear that you …

[MDEP-849] Replace Maven shared StringUtils with Commons Lang3

---

src/it/projects/copy-dependencies/pom.xml
src/main/java/org/apache/maven/plugins/dependency/AbstractDependencyMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/CopyMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/CopyDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/AbstractResolveMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestUnpackMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo2.java
src/test/resources/unit/unpack-dependencies-test/plugin-config.xml

[MDEP-855] Remove unused and ignored parameter - useJvmChmod

---

src/main/java/org/apache/maven/plugins/dependency/PurgeLocalRepositoryMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/AbstractDependencyFilterMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/BuildClasspathMojo.java
src/main/java/org/apache/maven/plugins/dependency/utils/DependencyUtil.java
src/main/java/org/apache/maven/plugins/dependency/utils/UnpackUtil.java
src/main/java/org/apache/maven/plugins/dependency/utils/translators/ClassifierTypeTranslator.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo.java

Continuation of https://issues.apache.org/jira/browse/MNG-6829
Use this link to re-run the recipe: https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?organizationId=QXBhY2hlIE1hdmVu
Review requested of @elharo 
If your pull request is …

[MNG-6829] Replace any StringUtils#isEmpty(String) and #isNotEmpty(String)

---

src/site/site.xml
src/site/xdoc/download.xml.vm

[MDEP-866] Refresh download page

---

src/main/java/org/apache/maven/plugins/dependency/ListRepositoriesMojo.java

MDEP-875 prevent possible NPE

---

pom.xml

[MDEP-883] - Upgrade maven-plugin parent to 40

---

src/it/projects/sources/module-a/pom.xml
src/it/projects/sources/module-b/pom.xml
src/main/java/org/apache/maven/plugins/dependency/resolvers/ResolveDependencySourcesMojo.java

As described in [MDEP-895](https://issues.apache.org/jira/browse/MDEP-895), when running the `sources` goal against a multi-module project, the plugin is expecting all submodules to have been previously compiled. This shouldn't be necessary - even if the project in question generated its own sources, they shouldn't be needed, since they are _included_ in the project.
is to use the JIRA issue title in the pull request title and in …

[MDEP-895] - dependency:sources fails for multi-module project

---

pom.xml

https://issues.apache.org/jira/browse/MDEP-912

[MDEP-912] Use version for plexus-utils/plexus-xml from parent

---

src/it/mrm/settings.xml

https://issues.apache.org/jira/browse/MDEP-918

[MDEP-918] Use standard updatePolicy for repositories in ITs

---

src/it/projects/copy-from-remote-repository/pom.xml
src/it/projects/unpack-from-remote-repository/pom.xml

https://issues.apache.org/jira/browse/MDEP-919

[MDEP-919] Fix ITs for Maven4

---

pom.xml
src/test/java/org/apache/maven/plugins/dependency/AbstractDependencyMojoTest.java
src/test/java/org/apache/maven/plugins/dependency/analyze/TestAnalyzeDepMgt.java

https://issues.apache.org/jira/browse/MDEP-925

[MDEP-925] Require Maven 3.6.3

---

pom.xml
src/main/java/org/apache/maven/plugins/dependency/ListClassesMojo.java
src/main/java/org/apache/maven/plugins/dependency/utils/ParamArtifact.java
src/main/java/org/apache/maven/plugins/dependency/utils/ResolverUtil.java
src/test/java/org/apache/maven/plugins/dependency/AbstractDependencyMojoTestCase.java
src/test/java/org/apache/maven/plugins/dependency/TestListClassesMojo.java
src/test/java/org/apache/maven/plugins/dependency/testUtils/stubs/DependencyProjectStub.java
src/test/java/org/apache/maven/plugins/dependency/utils/ResolverUtilTest.java

https://issues.apache.org/jira/browse/MDEP-924

[MDEP-924] Get rid of maven-artifact-transfer from list-classes goal

---

pom.xml
src/it/projects/analyze-excluded-classes/invoker.properties
src/it/projects/analyze-excluded-classes/pom.xml
src/it/projects/analyze-excluded-classes/setup.groovy
src/it/projects/analyze-excluded-classes/src/main/java/Main.java
src/it/projects/analyze-excluded-classes/verify.groovy
src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java
src/main/java/org/apache/maven/plugins/dependency/analyze/AnalyzeReportMojo.java

https://issues.apache.org/jira/browse/MDEP-928

[MDEP-928] Allow excluding classes from dependency:analyze

---

src/test/java/org/apache/maven/plugins/dependency/tree/TestTreeMojo.java

https://issues.apache.org/jira/browse/MDEP-710

[MDEP-710] re-enable test in TestTreeMojo

---

src/it/projects/tree/expected.txt
src/it/projects/tree/pom.xml
src/it/projects/tree/test.properties
src/it/projects/tree/verify.groovy

https://issues.apache.org/jira/browse/MDEP-835

[MDEP-835] Add optional dependency for tree IT

---

src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/AbstractFromConfigurationMojo.java

property = "mdep.overIfNewer" is incorrect as a mismatch on the naming and should have been "mdep.overWriteIfNewer" to respect naming convention as all others do.  All examples show using the more general property as 'overWriteIfNewer' so its odd to pass -Dmdep.overIfNewer instead of expected correct value.  I suspect this is a rare situation and was not an issue that I had but something I noticed when reviewing the code.  The original PR I opened #285 went unmerged and was requested to add a deprecated property for the original along with jira.  Due to how its used, I didn't see a very good way to make the invalid usage populate the correct one.  Maybe there is a better way here.  So for now, the misnamed original 'mdep.overIfNewer' is over a property that is unused simply noting its …

MDEP-938] Correct invalid property name and add deprecated old one

---

src/main/java/org/apache/maven/plugins/dependency/utils/DependencyUtil.java
src/test/java/org/apache/maven/plugins/dependency/utils/TestDependencyUtil.java

https://issues.apache.org/jira/browse/MDEP-943

[MDEP-943] Fix appendOutput option

---

src/main/java/org/apache/maven/plugins/dependency/GetMojo.java
src/site/apt/usage.apt.vm

https://issues.apache.org/jira/browse/MDEP-945

[MDEP-945] Fix documentation about get goal

---

src/site/apt/index.apt.vm

- [] You have run the integration tests successfully (`mvn -Prun-its clean verify`).
[ERROR] The following builds failed:
[ERROR] *  list-repositories\pom.xml
[Individual Contributor License …

MDEP-913 Add dependency:collect on index-page

---

src/it/projects/mdep-439-analyze-java8/invoker.properties
src/it/projects/mdep-571-resolve-java9/invoker.properties
src/it/projects/purge-local-repository-bad-dep/invoker.properties
src/it/projects/purge-local-repository-bad-pom/invoker.properties
src/it/projects/purge-local-repository-include/invoker.properties
src/it/projects/purge-local-repository-reresolve/invoker.properties
src/it/projects/purge-local-repository-version-range/invoker.properties

Remove outdated invoker conditions

---

src/site/apt/usage.apt.vm

General copy editing, including removal of content that only applies to pre-Maven 2.0.6 projects.

[MNGSITE-393] Cleanup and correct usage docs

---

src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java

Let's see if anything breaks if we clean this up.

Replace old workaround for Maven 3.2.5 bug

---

src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/AbstractFromConfigurationMojo.java

Delete obsolete commented code for 20 year old issue that was won't fixed 10 years ago

Delete obsolete commented code

---

src/test/java/org/apache/maven/plugins/dependency/tree/TestTreeMojo.java

[MDEP-930] Make test robust against platform default character sets

---

src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java

1. Don't bother with `@since` from 2.0 versions
3. Fix copy pasta

Clean up parameters docs

---

pom.xml
src/test/java/org/apache/maven/plugins/dependency/AbstractDependencyMojoTestCase.java
src/test/java/org/apache/maven/plugins/dependency/utils/filters/TestDestFileFilter.java
src/test/java/org/apache/maven/plugins/dependency/utils/filters/TestMarkerFileFilter.java
src/test/java/org/apache/maven/plugins/dependency/utils/filters/TestResolveMarkerFileFilter.java
src/test/java/org/apache/maven/plugins/dependency/utils/markers/TestDefaultMarkerFileHandler.java
src/test/java/org/apache/maven/plugins/dependency/utils/markers/TestUnpackMarkerFileHandler.java

Gets rid of the dependency on commons-io

Convert to JUnit 5

---

src/test/java/org/apache/maven/plugins/dependency/TestCollectMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestCopyMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestUnpackMojo.java
src/test/java/org/apache/maven/plugins/dependency/resolvers/TestResolveMojo.java

These aren't needed in these tests

Remove invocations of now deprecated methods we want to delete

---

src/it/projects/copy-and-unpack-with-alternate-local-repo/verify.bsh
src/it/projects/copy-cli/verify.bsh
src/it/projects/copy-dependencies/verify.bsh
src/it/projects/copy-from-reactor/verify.bsh
src/it/projects/copy-from-remote-repository/verify.bsh
src/it/projects/copy-with-prependGroupId/verify.bsh
src/it/projects/copy/verify.bsh
src/it/projects/get-artifact-maven-plugin/verify.bsh
src/it/projects/get-artifact-no-transitive/verify.bsh
src/it/projects/get-artifact/verify.bsh
src/it/projects/get-gav/verify.bsh
src/it/projects/purge-local-repository-bad-pom/verify.bsh
src/it/projects/purge-local-repository-multi-module-execution/setup.bsh
src/it/projects/purge-local-repository-multi-module-execution/verify.bsh
src/it/projects/purge-local-repository-multi-module/setup.bsh
src/it/projects/purge-local-repository-non-transitive/verify.bsh
src/it/projects/purge-local-repository-reresolve/verify.bsh
src/it/projects/purge-local-repository-snapshots-only/setup.bsh
src/it/projects/purge-local-repository-snapshots-only/verify.bsh
src/it/projects/purge-local-repository-version-range/verify.bsh
src/it/projects/purge-local-repository-without-pom/setup.bsh
src/it/projects/purge-local-repository/setup.bsh
src/it/projects/purge-local-repository/verify.groovy
src/it/projects/unpack-cli/verify.bsh
src/it/projects/unpack-dependencies/verify.groovy
src/it/projects/unpack-from-remote-repository/verify.bsh
src/it/projects/unpack/verify.bsh

The general principle is that passing tests generate no output.

Reduce noise from passing integration tests

---

src/site/apt/index.apt.vm

Fixes [#678](https://github.com/apache/maven-site/issues/678)

Update collect URL

---

src/test/java/org/apache/maven/plugins/dependency/utils/filters/TestMarkerFileFilter.java

A couple got missed in the transition to JUnit 4.

Enable tests

---

.github/workflows/pr-automation.yml
.github/workflows/stale.yml

Add PR Automation and Stale actions

---

pom.xml

Following this checklist to help us incorporate your
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
To make clear that you license your contribution under
you have to acknowledge this by using the following check-box.

fix: remove duplicate maven-resolver-api and maven-resolver-util dependencies in pom.xml

---

src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/AbstractFromConfigurationMojo.java

Following this checklist to help us incorporate your
Fixes https://issues.apache.org/jira/browse/MDEP-967
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
To make clear that you license your contribution under
you have to acknowledge this by using the following check-box.

[MDEP-967] Change info to debug logging in AbstractFromConfigurationMojo
