apache/maven-dependency-plugin

pom.xml
src/it/projects/unpack-dependencies-with-filemappers/invoker.properties
src/it/projects/unpack-dependencies-with-filemappers/pom.xml
src/it/projects/unpack-dependencies-with-filemappers/verify.groovy
src/main/java/org/apache/maven/plugins/dependency/AbstractDependencyMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/ArtifactItem.java
src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/UnpackMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/UnpackDependenciesMojo.java
src/site/apt/examples/unpacking-filemapper.apt.vm
src/site/apt/index.apt.vm
src/site/site.xml

Solving [MDEP-628](https://issues.apache.org/jira/browse/MDEP-628).
The new parameter `fileMappers` (default: `null`) can be set to an implementation of the `org.codehaus.plexus.components.io.filemappers.FileMapper` interface to rewrite the target path of each unpacked file.
This is useful in case prefixes of target files names within the target directory shall be added (using `PrefixFileMapper`), changed or omitted (using `RegExpFileMapper`).

[MDEP-628] Parameter `fileMappers` for unpack path rewriting

---

pom.xml
src/it/mrm/repository/ResourceArtifact-1.0.jar/resource1.txt
src/it/mrm/repository/ResourceArtifact-1.0.jar/resource2.txt
src/it/mrm/repository/ResourceArtifact-1.0.pom
src/it/projects/mdep-586-unpacking-resources/pom.xml
src/it/projects/mdep-586-unpacking-resources/verify.groovy

According to the issue MDEP-586, it is not possible to unpack different files from the same JAR file in N distinct folders. In this pull request, I used the configuration parameter **markersDirectory** to setup folders containing the dependencies marked for each directory. The dependencies will only be marked at each execution of **unpack-dependencies** goal in their respective folder, so one execution will not dirty the folder of another execution.
In my view, I do not think this is a bug.
where you …

[MDEP-586] Unpacking different resources into different location from the same artifact do work.

---

src/it/projects/tree/invoker.properties

Following this checklist to help us incorporate your contribution quickly and easily:
To make clear that you license your contribution under  the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) you have to acknowledge this by using the following check-box.
When investigating [MDEP-666](https://issues.apache.org/jira/browse/MDEP-666) I noticed that the `tree` goal has both the unit tests and the integration tests disabled. The integration test works fine on my machine, and I'd love to see it enabled.
It would help a lot when actually fixing the aforementioned issue. I also tried re-enabling the unit tests, but they failed. Since they are in fact in-between unit and integration level, I'd rather leave them for now and add proper unit tests when fixing …

[MDEP-666] Re-enable integration test for tree goal

---

CONTRIBUTING.md
README.md
src/site/apt/index.apt.vm

The link to dev-list was broken on the `README.md`.
I took the liberty to also fix other occurences of this link.

(doc) Fix broken link to developpers mailing list

---

src/site/apt/examples/resolving-conflicts-using-the-dependency-tree.apt

Running `mvn dependency:tree -Dverbose` as suggested in docs produces non-verbose output and the following warning:
```
[INFO] --- maven-dependency-plugin:3.0.0:tree (default-cli) @ my-project ---
[INFO] Verbose not supported since maven-dependency-plugin 3.0
...
```
From what I gather, it was originally reported as [MDEP-374](https://issues.apache.org/jira/browse/MDEP-374) back in 2.8, then a workaround based on Maven2 was introduced only to be removed later with [MDEP-494](https://issues.apache.org/jira/browse/MDEP-494).
This PR updates documentation with a possible workaround.
--
require a JIRA issue.  Your …

(doc) - Add note on dependecy:tree -Dverbose support in 3.0+

---

pom.xml

@hboutemy the upgrade broke one of the integration tests. Fixing this is going to require moving to Maven 3.1 as a minimum which requires some other changes.

[MDEP-676] fix test

---

src/main/java/org/apache/maven/plugins/dependency/analyze/AnalyzeDepMgt.java

[MNGSITE-393] don't care about old versions

---

src/main/java/org/apache/maven/plugins/dependency/analyze/AnalyzeDepMgt.java
src/test/java/org/apache/maven/plugins/dependency/testUtils/stubs/DependencyProjectStub.java

Clean up dead code

---

src/main/java/org/apache/maven/plugins/dependency/GetMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/ResolveDependenciesMojo.java
src/main/resources/analyze-report_en.properties

docs: fix typo

---

src/main/java/org/apache/maven/plugins/dependency/GetClassesMojo.java
src/main/java/org/apache/maven/plugins/dependency/ListClassesMojo.java
src/test/java/org/apache/maven/plugins/dependency/TestGetClassesMojo.java

[MDEP-645] Created new mojo GetClassesMojo which lists all class dependencies for a specified artifact.

---

src/test/java/org/apache/maven/plugins/dependency/AbstractDependencyMojoTestCase.java
src/test/java/org/apache/maven/plugins/dependency/testUtils/stubs/StubDefaultFileMarkerHandler.java
src/test/java/org/apache/maven/plugins/dependency/testUtils/stubs/StubMarkerFile.java
src/test/java/org/apache/maven/plugins/dependency/testUtils/stubs/StubSourcesFileMarkerHandler.java

remove todos and other IDE inserted boilerplate

---

src/site/apt/usage.apt.vm

Little typo in dependency:tree who handle the parameter outputFile instead of output
please ask on the …

Correct typo for depencency:tree -DoutputFile

---

pom.xml

Reverts apache/maven-dependency-plugin#111, due to [my comment there](https://github.com/apache/maven-dependency-plugin/pull/111#issuecomment-707643034):
> This upgrade is necessary to fix [MDEP-651](https://issues.apache.org/jira/browse/MDEP-651), but some tests are failing on my machine. Need to investigate before I'd merge.

Revert "Bump plexus-archiver from 4.2.2 to 4.2.3"

---

src/site/apt/index.apt.vm

The link to _source repository_ points to a non-existing page.
Modified the link to the appropriate page.

Fix source repo link

---

pom.xml

The current transitive dependency `commons-beanutils-1.7.0` is vulnerable: https://www.cve.org/CVERecord?id=CVE-2014-0114.

Update transitive dependency to non-vulnerable version

---

src/it/projects/mdep-779-analyze-only-verbose-shows-class-names/invoker.properties
src/it/projects/mdep-779-analyze-only-verbose-shows-class-names/pom.xml
src/it/projects/mdep-779-analyze-only-verbose-shows-class-names/src/main/java/usedUndeclaredReference/Project.java
src/it/projects/mdep-779-analyze-only-verbose-shows-class-names/verify.bsh
src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java

This adds [the class names tracked in this PR](https://github.com/apache/maven-dependency-analyzer/pull/44) to the UI, when `-Dverbose` is set:
```
[WARNING] Used undeclared dependencies found:
[WARNING]    xml-apis:xml-apis:jar:1.0.b2:compile
[WARNING]       class org.apache.xmlcommons.Version
[WARNING] Unused declared dependencies found:
[WARNING]    dom4j:dom4j:jar:1.6.1:compile
```
It also includes the small changes necessary for any upgrade of `maven-dependency-analyzer` to `1.12`.
To allow this to be reviewed ahead of a release of `maven-dependency-analyzer`, the version is set to `1.12.0-SNAPSHOT`; if approved, it'll presumably be `1.12.0`. As mentioned, it ties the new output to `-Dverbose`; I think this is simpler than adding a new specific property, and less disruptive than …

MDEP-779 show class names used in undeclared dependencies

---

src/it/projects/analyze-ignore-all-non-test-scope-dependency/invoker.properties
src/it/projects/analyze-ignore-all-non-test-scope-dependency/pom.xml
src/it/projects/analyze-ignore-all-non-test-scope-dependency/src/test/java/MainTest.java
src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java

Implements a flag that allows ignoring non-test scoped dependencies
when they are used only in test scope.
Includes integration test that verifies the behavior.
the [Apache License Version 2.0, January …

[MDEP-804] - Allow auto-ignore of all non-test scoped dependencies used only in test scope

---

pom.xml
src/main/java/org/apache/maven/plugins/dependency/analyze/AnalyzeReportMojo.java

[MDEP-826] Upgrade maven-reporting-imp from 3.1.0 to 3.2.0

---

pom.xml

[MDEP-831] remove unused beanutils dependency

---

pom.xml
src/main/java/org/apache/maven/plugins/dependency/DisplayAncestorsMojo.java
src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/ResolveDependencySourcesMojo.java

[MDEP-831] Remove dependency on commons-lang3

---

src/main/java/org/apache/maven/plugins/dependency/ListClassesMojo.java
src/test/java/org/apache/maven/plugins/dependency/TestListClassesMojo.java

[MDEP-843] Use GAV fields to support them as parameters

---

pom.xml
src/it/projects/unpack-custom-ear/verify.groovy
src/main/java/org/apache/maven/plugins/dependency/AbstractDependencyMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/UnpackMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/UnpackDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/utils/UnpackUtil.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestIncludeExcludeUnpackMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestUnpackMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo2.java

Methods for unpack artifacts are in AbstractDependencyMojo but are only used by unpack and unpack-dependencies mojos.
We can create separate component and use only where is needed.
---
[Individual Contributor …

[MDEP-859] Code refactor - UnpackUtil

---

src/site/apt/usage.apt.vm

Trivial change with no effect on build so I can see if the CI is broken at head or not

Tighten language

---

pom.xml
src/main/java/org/apache/maven/plugins/dependency/analyze/AnalyzeDuplicateMojo.java

[MDEP-832] - Remove commons-collections-4

---

src/main/java/org/apache/maven/plugins/dependency/tree/BuildingDependencyNodeVisitor.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo2.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/resolvers/ResolveDependenciesMojoTest.java

As discussed on
- https://github.com/apache/maven-scm/pull/184
- https://issues.apache.org/jira/browse/MNG-6847
Review requested of @elharo
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.UseDiamondOperator?organizationId=QXBhY2hlIE1hdmVu
----
be performed on your pull request …

[MNG-6847] Use diamond operator

---

src/main/java/org/apache/maven/plugins/dependency/fromDependencies/BuildClasspathMojo.java
src/main/java/org/apache/maven/plugins/dependency/utils/DependencyUtil.java

* using Files.newBufferedWriter(), Files.lines()
* using reader.lines().forEach()
* Removed inverse logic.
* Using StandardCharsets.UTF_8 instead of literal texts.
[Individual Contributor License …

Code Improvements

---

pom.xml
src/it/projects/analyze-invalid-exclude-multumodule-project/invoker.properties
src/it/projects/analyze-invalid-exclude-multumodule-project/module1/pom.xml
src/it/projects/analyze-invalid-exclude-multumodule-project/module1/src/main/java/foo/Main.java
src/it/projects/analyze-invalid-exclude-multumodule-project/module2/pom.xml
src/it/projects/analyze-invalid-exclude-multumodule-project/module2/src/main/java/foo/Main.java
src/it/projects/analyze-invalid-exclude-multumodule-project/pom.xml
src/it/projects/analyze-invalid-exclude-multumodule-project/verify.groovy
src/it/projects/analyze-invalid-exclude/invoker.properties
src/it/projects/analyze-invalid-exclude/pom.xml
src/it/projects/analyze-invalid-exclude/src/main/java/Main.java
src/it/projects/analyze-invalid-exclude/verify.groovy
src/main/java/org/apache/maven/plugins/dependency/exclusion/AnalyzeExclusionsMojo.java
src/main/java/org/apache/maven/plugins/dependency/exclusion/Coordinates.java
src/main/java/org/apache/maven/plugins/dependency/exclusion/ExclusionChecker.java
src/site/apt/index.apt.vm
src/site/apt/usage.apt.vm
src/test/java/org/apache/maven/plugins/dependency/exclusion/AnalyzeExclusionsMojoTest.java
src/test/java/org/apache/maven/plugins/dependency/exclusion/ExclusionCheckerTest.java
src/test/resources/unit/analyze-exclusions/plugin-config.xml

This mojo reports if exclusions are defined on a dependency, but that dependency does not pull in said artifacts.
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are …

[MDEP-317] - add mojo to analyze invalid exclusions

---

src/it/projects/analyze-invalid-exclude-multumodule-project/module2/pom.xml
src/it/projects/analyze-invalid-exclude-multumodule-project/pom.xml
src/it/projects/analyze-invalid-exclude/pom.xml
src/main/java/org/apache/maven/plugins/dependency/exclusion/AnalyzeExclusionsMojo.java
src/main/java/org/apache/maven/plugins/dependency/utils/ResolverUtil.java
src/test/java/org/apache/maven/plugins/dependency/exclusion/AnalyzeExclusionsMojoTest.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestUnpackMojo.java

https://issues.apache.org/jira/browse/MDEP-917

[MDEP-917] dependency:analyze-exclusions - use Resolver API instead of ProjectBuilder

---

src/it/mrm/repository/a-with-dep.pom
src/it/mrm/repository/b-with-dep.pom
src/it/mrm/repository/c-without-dep.pom
src/it/projects/analyze-invalid-exclude-multumodule-project/module1/pom.xml
src/it/projects/analyze-invalid-exclude-multumodule-project/pom.xml
src/it/projects/analyze-invalid-exclude-multumodule-project/verify.groovy
src/it/projects/analyze-invalid-exclude/pom.xml
src/it/projects/analyze-invalid-exclude/verify.groovy
src/main/java/org/apache/maven/plugins/dependency/exclusion/AnalyzeExclusionsMojo.java
src/main/java/org/apache/maven/plugins/dependency/exclusion/Coordinates.java
src/main/java/org/apache/maven/plugins/dependency/exclusion/ExclusionChecker.java
src/test/java/org/apache/maven/plugins/dependency/exclusion/AnalyzeExclusionsMojoTest.java
src/test/java/org/apache/maven/plugins/dependency/exclusion/ExclusionCheckerTest.java

https://issues.apache.org/jira/browse/MDEP-922

[MDEP-922] dependency:analyze-exclusions - should report issue only in current project

---

src/main/java/org/apache/maven/plugins/dependency/resolvers/CollectDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/ResolveDependenciesMojo.java

https://issues.apache.org/jira/browse/MDEP-914

[MDEP-914] Fix link in collect goal description

---

src/main/java/org/apache/maven/plugins/dependency/AbstractDependencyMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/CopyMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/CopyDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/ResolveDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/ResolvePluginsMojo.java
src/main/java/org/apache/maven/plugins/dependency/utils/CopyUtil.java
src/test/java/org/apache/maven/plugins/dependency/AbstractDependencyMojoTestCase.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java

this method is only needed in CopyMojo and CopyDependenciesMojo so it is not needed in AbstractDependencyMojo

[MDEP-923] Extract copyFile method from AbstractDependencyMojo

---

src/main/java/org/apache/maven/plugins/dependency/tree/TreeMojo.java

Only simple info for #391 - more detail documentation is still needed

[MDEP-799] Add simple info json format for tree and cleanups

---

src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/CopyMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/CopyDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/AbstractResolveMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/ResolvePluginsMojo.java

next code cleanups ...
in next step we cen remove `AbstractResolveMojo`

[MDEP-923] Move methods in place where are used

---

src/it/projects/sources/test.properties
src/main/java/org/apache/maven/plugins/dependency/resolvers/ResolveDependencySourcesMojo.java

[MDEP-939] Lock down classifier in dependency:sources goal

---

src/main/java/org/apache/maven/plugins/dependency/fromDependencies/AbstractDependencyFilterMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/CopyDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/ResolvePluginsMojo.java
src/main/java/org/apache/maven/plugins/dependency/utils/translators/ArtifactTranslator.java
src/main/java/org/apache/maven/plugins/dependency/utils/translators/ClassifierTypeTranslator.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo2.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/utils/translators/TestClassifierTypeTranslator.java

https://issues.apache.org/jira/browse/MDEP-940

[MDEP-940] Use Resolver API instead of m-a-t for resolving artifacts

---

src/main/java/org/apache/maven/plugins/dependency/fromDependencies/AbstractFromDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/CopyDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo.java

If I understand it correctly, if a Mojo parameter has a `@Parameter#defaultValue`, that value overwrites the initial value of the field (if any).
This pull request therefore fixes two cases where the initial field value did not match the `@Parameter#defaultValue`, which could have lead to confusion.
- For `AbstractFromDependenciesMojo#failOnMissingClassifierArtifact` it seems this issue was accidentally introduced by https://github.com/apache/maven-dependency-plugin/commit/1592cdc1979b90c9f59765affd47ec49cca38ec7#diff-b352be9b15d48a15ddf79e115c28c4cc776b7ec2662f553e189a978261d34881R100; the Javadoc had previously `default-value="true"`, which was matching the field value `true`, and was accidentally changed to `false`.
Though I am not going to adjust the default value to be `true` again …

Fix mismatching Parameter initial field values

---

src/it/projects/analyze/pom.xml
src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java

slf4j-simple is a super common "unused" dependency because when slfj-api or slf4j-impl is included and slf4j-simple isn't, the application works just fine but prints an annoying log message to the console telling developers to add it.
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```
or 
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
so devs deliberately add slf4j-simple to their dependencies just to shut up these warnings.
see https://www.slf4j.org/manual.html

[MDEP-957] By default, don't report slf4j-simple as unused

---

src/main/java/org/apache/maven/plugins/dependency/utils/DependencyUtil.java

This method initially confused me, so once I figured out what it was doing I added a comment. No behavioral changes.

Elaborate on DependencyUtil.log in doc comment

---

src/main/java/org/apache/maven/plugins/dependency/AbstractDependencyMojo.java
src/test/java/org/apache/maven/plugins/dependency/TestCollectMojo.java
src/test/java/org/apache/maven/plugins/dependency/resolvers/TestResolveMojo.java
src/test/java/org/apache/maven/plugins/dependency/utils/TestSilentLog.java

[MDEP-960] Repair silent logging

---

src/test/java/org/apache/maven/plugins/dependency/tree/TestTreeMojo.java

This pull request addresses the flakiness in the following tests within the class [org.apache.maven.plugins.dependency.tree.TestTreeMojo](https://github.com/apache/maven-dependency-plugin/blob/b19b7e027085fb215f8f510d7bef8033ecbd4d48/src/test/java/org/apache/maven/plugins/dependency/tree/TestTreeMojo.java#L54):
1. [TestTreeMojo#testTreeTestEnvironment](https://github.com/apache/maven-dependency-plugin/blob/b19b7e027085fb215f8f510d7bef8033ecbd4d48/src/test/java/org/apache/maven/plugins/dependency/tree/TestTreeMojo.java#L83)
2. [TestTreeMojo#testTreeJsonParsing](https://github.com/apache/maven-dependency-plugin/blob/b19b7e027085fb215f8f510d7bef8033ecbd4d48/src/test/java/org/apache/maven/plugins/dependency/tree/TestTreeMojo.java#L180)
These tests exhibit flakiness due to non-deterministic …

Fixing flaky tests in TestTreeMojo

---

src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java

This Pull Request addresses test flakiness in the following test:
[`org.apache.maven.plugins.dependency.fromDependencies.TestCopyDependenciesMojo#testGetDependencies`](https://github.com/apache/maven-dependency-plugin/blob/c729702b18a9b496049b0994db7426c72339be75/src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java#L566)
The test performs a `String` equality check on the content of dependencies stored in `mojo.resolvedDependencies` against dependencies resolved through `mojo.getDependencySets(true).getResolvedDependencies()`.
Since these dependencies are stored in `java.util.Set` collections, their ordering is non-deterministic, which occasionally causes test failures when executed with the Nondex plugin.
To address this, I modified the test to …

Fixing flaky test in TestCopyDependenciesMojo

---

src/main/java/org/apache/maven/plugins/dependency/fromDependencies/AbstractDependencyFilterMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/BuildClasspathMojo.java
src/test/java/org/apache/maven/plugins/dependency/analyze/TestAnalyzeDuplicateMojo.java
src/test/java/org/apache/maven/plugins/dependency/exclusion/AnalyzeExclusionsMojoTest.java
src/test/java/org/apache/maven/plugins/dependency/resolvers/ResolveDependenciesMojoTest.java

and add some Override annotations

Cleanup a few obsolete TODOs

---

src/test/java/org/apache/maven/plugins/dependency/testUtils/stubs/StubUnpackFileMarkerHandler.java

This relies on getIncludes and getExcludes never returning null, which is currently true. Since this is all in src/test this reasonably safe and should have no effect on production.

[MDEP-952] Break dependency on commons-lang3

---

src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/UnpackMojo.java

Includes and excludes can't be null so this method was never needed.

[MDEP-952] Remove StringUtils from UnpackMojo

---

src/main/java/org/apache/maven/plugins/dependency/analyze/AnalyzeDepMgt.java

In this case the simplest thing that could possibly work is to simply not strip the colon from the end. It's just a slightly uglier log message.

[MDEP-952] avoid StringUtils.stripEnd

---

src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/AbstractFromConfigurationMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/UnpackMojo.java

Needs a closer look. This appears to be the change that caused the bug MDEP-952
```
Running post-build script: /Users/elharo/maven-dependency-plugin/target/it/mdep-952-unpack-fails-if-extension-of-artifact-is-used/verify.groovy
Assertion failed: 
assert buildLog.contains( 'BUILD SUCCESS' )
|        |
|        false
```

[MDEP-952] Partially decouple AbstractFromConfigurationMojo from StringUtils

---

src/site/apt/usage.apt.vm

Most devs prefer / to \
and a couple of other minor edits

Unix file separators

---

pom.xml
src/main/java/org/apache/maven/plugins/dependency/fromDependencies/CopyDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/utils/CopyUtil.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java

Fixes https://issues.apache.org/jira/browse/MDEP-972

[MDEP-972] copy-dependencies: copy signatures alongside artifacts

---

src/test/java/org/apache/maven/plugins/dependency/AbstractDependencyMojoTestCase.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestIncludeExcludeUnpackMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestIncludeExcludeUnpackDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo2.java

1. temp directories were always named "testDirStr" rather than the value of testDirStr
2. Avoid unneeded garbage collection

Clean up test teardown and temp directories

---

src/site/apt/index.apt.vm

There were actual two links for the same goal, one with the correct link, but at the bottom of the page.
The broken one was added later in "alphabetical correct" position.
I fixed the one at the top where it belongs and removed the one at the bottom with

Fix broken link for analyze-exclusions-mojo on usage-page

---

src/main/java/org/apache/maven/plugins/dependency/resolvers/CollectDependenciesMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/ResolveDependenciesMojo.java

Small Javadoc clarifications

---

src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/UnpackMojo.java

fixes #536 
Property attribute is missing in @Parameter annotation from markersDirectory attribute in UnpackMojo due to which its not working from command line.

Fix - markersDirectory is not working when unpack goal is executed from command line 

---

pom.xml
src/it/projects/mdep-779-analyze-only-verbose-shows-class-names/pom.xml
src/it/projects/mdep-779-analyze-only-verbose-shows-class-names/src/main/java/usedUndeclaredReference/Project.java
src/it/projects/mdep-779-analyze-only-verbose-shows-class-names/verify.bsh

This commit updates the analyser version which supports reading byte code generated by Java 24.
Fixes #524
Following this checklist to help us incorporate your
Note that commits might be squashed by a maintainer on merge.
Build Summary:
[INFO]   Passed: 84, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  mdep-779-analyze-only-verbose-shows-class-names/pom.xml
This IT test passes without the analyzer update. I'll take a look later when I have time to see if I see whats failing, tho I'm unfamiliar with both code bases.
To make clear that you license your contribution under
you …

Update maven-dependency-analyzer to support Java24

---

src/main/java/org/apache/maven/plugins/dependency/analyze/AbstractAnalyzeMojo.java
src/site/apt/examples/exclude-dependencies-from-dependency-analysis.apt.vm

see https://github.com/apache/maven-dependency-plugin/pull/459 and #1458

[MEDP-964] unconditionally ignore dependencies known to be loaded by reflection

---

src/test/java/org/apache/maven/plugins/dependency/AbstractDependencyMojoTestCase.java
src/test/java/org/apache/maven/plugins/dependency/TestCollectMojo.java
src/test/java/org/apache/maven/plugins/dependency/TestGetMojo.java
src/test/java/org/apache/maven/plugins/dependency/TestListClassesMojo.java
src/test/java/org/apache/maven/plugins/dependency/TestPropertiesMojo.java
src/test/java/org/apache/maven/plugins/dependency/exclusion/AnalyzeExclusionsMojoTest.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestArtifactItem.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestCopyMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestIncludeExcludeUnpackMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestUnpackMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestBuildClasspathMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo2.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestIncludeExcludeUnpackDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo2.java
src/test/java/org/apache/maven/plugins/dependency/resolvers/GoOfflineMojoTest.java
src/test/java/org/apache/maven/plugins/dependency/resolvers/ResolveDependenciesMojoTest.java
src/test/java/org/apache/maven/plugins/dependency/resolvers/TestResolveMojo.java
src/test/java/org/apache/maven/plugins/dependency/tree/TestTreeMojo.java
src/test/java/org/apache/maven/plugins/dependency/utils/TestDependencyStatusSets.java
src/test/java/org/apache/maven/plugins/dependency/utils/translators/TestClassifierTypeTranslator.java

Following this checklist to help us incorporate your
Fixes https://github.com/apache/maven-dependency-plugin/issues/1486
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
To make clear that you license your contribution under
you have to acknowledge this by using the following check-box.

Clean up AbstractDependencyMojoTestCase setUp

---

pom.xml

some test are flaky, try to re-run it make build more stable
tests generate many debug outputs, it is not needed by default

Re-run failed tests and redirect outputs from tests to file

---

src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/AbstractFromConfigurationMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/CopyMojo.java
src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/UnpackMojo.java
src/test/java/org/apache/maven/plugins/dependency/exclusion/AnalyzeExclusionsMojoTest.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestCopyMojo.java
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestUnpackMojo.java
src/test/java/org/apache/maven/plugins/dependency/utils/translators/TestClassifierTypeTranslator.java

Next step to remove maven-artifact-transfer and legacy staff

Use Resolver API in copy and unpack

---

pom.xml
src/it/projects/analyze-excluded-classes/verify.groovy
src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestCopyMojo.java

Bump Maven in dependencies to 3.9.11

---

src/main/java/org/apache/maven/plugins/dependency/fromDependencies/AbstractDependencyFilterMojo.java

We should set new properties on copy of ProjectBuildingRequest not on one returned by MavenSession
In other case change can have impact on whole MavenSession

ProjectBuildingRequest should not be modified

---

src/main/java/org/apache/maven/plugins/dependency/AbstractDependencyMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/AbstractResolveMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/GoOfflineMojo.java
src/main/java/org/apache/maven/plugins/dependency/resolvers/ResolvePluginsMojo.java
src/main/java/org/apache/maven/plugins/dependency/utils/ResolverUtil.java
src/test/java/org/apache/maven/plugins/dependency/AbstractDependencyMojoTest.java

- use the same method for generating plugin list as in resolve-plugin
- move parameter where is used
- move some method where is used
- cleanups

Use Resolver API in go-offline for plugins resolving
